"""Add Week 4 P0 persistence without inferring legacy decision links.

This migration is strictly additive. Existing ``risk_decisions`` remain intact
and unlinked because their relationship to a Week 4 recommendation is ambiguous
without a stable source recommendation identifier.

Revision ID: 20260730_0007
Revises: 20260724_0006
Create Date: 2026-07-30 12:43:56.878293
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260730_0007"
down_revision: str | None = "20260724_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qa_decision_reviews",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("suggested_decision", sa.String(length=40), nullable=False),
        sa.Column("final_decision", sa.String(length=40), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("actor_role", sa.String(length=120), nullable=False),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("previous_review_id", sa.String(length=64), nullable=True),
        sa.Column("external_action_executed", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "final_decision IS NULL OR final_decision IN "
            "('GO', 'GO_WITH_CONDITIONS', 'NO_GO', 'INSUFFICIENT_INFORMATION')",
            name="ck_qa_decision_reviews_final_decision",
        ),
        sa.CheckConstraint(
            "status IN ('CONFIRMED', 'OVERRIDDEN', 'REJECTED')",
            name="ck_qa_decision_reviews_status",
        ),
        sa.CheckConstraint(
            "suggested_decision IN "
            "('GO', 'GO_WITH_CONDITIONS', 'NO_GO', 'INSUFFICIENT_INFORMATION')",
            name="ck_qa_decision_reviews_suggested_decision",
        ),
        sa.CheckConstraint(
            "external_action_executed = false", name="ck_qa_decision_reviews_no_external_action"
        ),
        sa.ForeignKeyConstraint(
            ["previous_review_id"], ["qa_decision_reviews.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["risk_analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_qa_decision_reviews_previous_review_id"),
        "qa_decision_reviews",
        ["previous_review_id"],
        unique=False,
    )
    op.create_index(
        "ix_qa_decision_reviews_project_snapshot_created",
        "qa_decision_reviews",
        ["project_id", "snapshot_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_qa_decision_reviews_snapshot_id"),
        "qa_decision_reviews",
        ["snapshot_id"],
        unique=False,
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("source_snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("source_risk_id", sa.String(length=64), nullable=False),
        sa.Column("policy_id", sa.String(length=100), nullable=False),
        sa.Column("risk_key", sa.String(length=64), nullable=False),
        sa.Column("recommendation_key", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("priority", sa.String(length=30), nullable=False),
        sa.Column("priority_score", sa.Integer(), nullable=False),
        sa.Column("priority_factors", sa.JSON(), nullable=False),
        sa.Column("priority_justification", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=30), nullable=False),
        sa.Column("impact", sa.String(length=30), nullable=False),
        sa.Column("effort", sa.String(length=30), nullable=False),
        sa.Column("urgency", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("original_payload", sa.JSON(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("assigned_to", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('PROPOSED', 'ACCEPTED', 'MODIFIED', 'REJECTED', 'COMPLETED')",
            name="ck_recommendations_status",
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_recommendations_confidence_range"
        ),
        sa.CheckConstraint(
            "priority_score >= 0 AND priority_score <= 100",
            name="ck_recommendations_priority_score_range",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_risk_id"], ["risks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_snapshot_id"], ["risk_analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_snapshot_id", "recommendation_key", name="uq_recommendations_snapshot_key"
        ),
    )
    op.create_index(
        op.f("ix_recommendations_policy_id"), "recommendations", ["policy_id"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_priority"), "recommendations", ["priority"], unique=False
    )
    op.create_index(
        "ix_recommendations_project_status_priority",
        "recommendations",
        ["project_id", "status", "priority_score"],
        unique=False,
    )
    op.create_index(
        "ix_recommendations_risk_key_status",
        "recommendations",
        ["risk_key", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_source_risk_id"),
        "recommendations",
        ["source_risk_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_source_snapshot_id"),
        "recommendations",
        ["source_snapshot_id"],
        unique=False,
    )
    op.create_table(
        "recommendation_outcomes",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("recommendation_id", sa.String(length=64), nullable=False),
        sa.Column("baseline_snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("observed_snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("score_before", sa.Float(), nullable=False),
        sa.Column("score_after", sa.Float(), nullable=False),
        sa.Column("score_delta", sa.Float(), nullable=False),
        sa.Column("contributions_before", sa.JSON(), nullable=False),
        sa.Column("contributions_after", sa.JSON(), nullable=False),
        sa.Column("policies_before", sa.JSON(), nullable=False),
        sa.Column("policies_after", sa.JSON(), nullable=False),
        sa.Column("observation", sa.Text(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('NOT_YET_MEASURABLE', 'IMPROVEMENT_OBSERVED', "
            "'NO_IMPROVEMENT_OBSERVED', 'INSUFFICIENT_DATA')",
            name="ck_recommendation_outcomes_status",
        ),
        sa.ForeignKeyConstraint(["baseline_snapshot_id"], ["risk_analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["observed_snapshot_id"], ["risk_analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recommendation_id"], ["recommendations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "recommendation_id",
            "observed_snapshot_id",
            name="uq_recommendation_outcomes_observation",
        ),
    )
    op.create_index(
        op.f("ix_recommendation_outcomes_baseline_snapshot_id"),
        "recommendation_outcomes",
        ["baseline_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_outcomes_observed_snapshot_id"),
        "recommendation_outcomes",
        ["observed_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_outcomes_recommendation_id"),
        "recommendation_outcomes",
        ["recommendation_id"],
        unique=False,
    )
    op.create_table(
        "recommendation_transitions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("recommendation_id", sa.String(length=64), nullable=False),
        sa.Column("source_snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=30), nullable=True),
        sa.Column("to_status", sa.String(length=30), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("actor_role", sa.String(length=120), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.Column("previous_payload", sa.JSON(), nullable=True),
        sa.Column("resulting_payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_action_executed", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "to_status IN ('PROPOSED', 'ACCEPTED', 'MODIFIED', 'REJECTED', 'COMPLETED')",
            name="ck_recommendation_transitions_to_status",
        ),
        sa.CheckConstraint(
            "external_action_executed = false",
            name="ck_recommendation_transitions_no_external_action",
        ),
        sa.CheckConstraint("sequence >= 1", name="ck_recommendation_transitions_sequence_positive"),
        sa.ForeignKeyConstraint(["recommendation_id"], ["recommendations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_snapshot_id"], ["risk_analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "recommendation_id", "sequence", name="uq_recommendation_transitions_sequence"
        ),
    )
    op.create_index(
        "ix_recommendation_transitions_recommendation_created",
        "recommendation_transitions",
        ["recommendation_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_transitions_recommendation_id"),
        "recommendation_transitions",
        ["recommendation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_transitions_source_snapshot_id"),
        "recommendation_transitions",
        ["source_snapshot_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_recommendation_transitions_source_snapshot_id"),
        table_name="recommendation_transitions",
    )
    op.drop_index(
        op.f("ix_recommendation_transitions_recommendation_id"),
        table_name="recommendation_transitions",
    )
    op.drop_index(
        "ix_recommendation_transitions_recommendation_created",
        table_name="recommendation_transitions",
    )
    op.drop_table("recommendation_transitions")
    op.drop_index(
        op.f("ix_recommendation_outcomes_recommendation_id"), table_name="recommendation_outcomes"
    )
    op.drop_index(
        op.f("ix_recommendation_outcomes_observed_snapshot_id"),
        table_name="recommendation_outcomes",
    )
    op.drop_index(
        op.f("ix_recommendation_outcomes_baseline_snapshot_id"),
        table_name="recommendation_outcomes",
    )
    op.drop_table("recommendation_outcomes")
    op.drop_index(op.f("ix_recommendations_source_snapshot_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_source_risk_id"), table_name="recommendations")
    op.drop_index("ix_recommendations_risk_key_status", table_name="recommendations")
    op.drop_index("ix_recommendations_project_status_priority", table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_priority"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_policy_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_qa_decision_reviews_snapshot_id"), table_name="qa_decision_reviews")
    op.drop_index(
        "ix_qa_decision_reviews_project_snapshot_created", table_name="qa_decision_reviews"
    )
    op.drop_index(
        op.f("ix_qa_decision_reviews_previous_review_id"), table_name="qa_decision_reviews"
    )
    op.drop_table("qa_decision_reviews")
    # ### end Alembic commands ###
