"""recommendation episodes

Revision ID: 20260730_0008
Revises: 20260730_0007
Create Date: 2026-07-30 13:05:14.461442
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260730_0008"
down_revision: str | None = "20260730_0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recommendations", sa.Column("sprint_id", sa.String(length=64), nullable=True))
    op.add_column(
        "recommendations", sa.Column("last_seen_snapshot_id", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "recommendations", sa.Column("last_seen_risk_id", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "recommendations", sa.Column("resolved_snapshot_id", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "recommendations", sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "recommendations",
        sa.Column("observation_count", sa.Integer(), nullable=False, server_default="1"),
    )
    op.add_column("recommendations", sa.Column("latest_evidence", sa.JSON(), nullable=True))
    op.add_column(
        "recommendations", sa.Column("latest_severity", sa.String(length=30), nullable=True)
    )
    op.add_column("recommendations", sa.Column("latest_score", sa.Float(), nullable=True))
    op.add_column("recommendations", sa.Column("latest_confidence", sa.Float(), nullable=True))
    op.execute(
        sa.text(
            """
            UPDATE recommendations
            SET sprint_id = (
                    SELECT sprint_id FROM risk_analyses
                    WHERE risk_analyses.id = recommendations.source_snapshot_id
                ),
                last_seen_snapshot_id = source_snapshot_id,
                last_seen_risk_id = source_risk_id,
                latest_evidence = evidence,
                latest_severity = severity,
                latest_score = (
                    SELECT score FROM risks
                    WHERE risks.id = recommendations.source_risk_id
                ),
                latest_confidence = confidence
            """
        )
    )
    with op.batch_alter_table("recommendations") as batch_op:
        batch_op.alter_column("last_seen_snapshot_id", nullable=False)
        batch_op.alter_column("last_seen_risk_id", nullable=False)
        batch_op.alter_column("observation_count", server_default=None)
        batch_op.alter_column("latest_evidence", nullable=False)
        batch_op.alter_column("latest_severity", nullable=False)
        batch_op.alter_column("latest_score", nullable=False)
        batch_op.alter_column("latest_confidence", nullable=False)
        batch_op.create_check_constraint(
            "ck_recommendations_observation_count_positive",
            "observation_count >= 1",
        )
    op.create_index(
        op.f("ix_recommendations_last_seen_risk_id"),
        "recommendations",
        ["last_seen_risk_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_last_seen_snapshot_id"),
        "recommendations",
        ["last_seen_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_resolved_snapshot_id"),
        "recommendations",
        ["resolved_snapshot_id"],
        unique=False,
    )
    op.create_index(
        "ix_recommendations_scope_active",
        "recommendations",
        ["project_id", "sprint_id", "resolved_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_sprint_id"), "recommendations", ["sprint_id"], unique=False
    )
    with op.batch_alter_table("recommendations") as batch_op:
        batch_op.create_foreign_key(
            "fk_recommendations_sprint_id_sprints",
            "sprints",
            ["sprint_id"],
            ["id"],
            ondelete="SET NULL",
        )
    with op.batch_alter_table("recommendations") as batch_op:
        batch_op.create_foreign_key(
            "fk_recommendations_last_seen_snapshot_id_risk_analyses",
            "risk_analyses",
            ["last_seen_snapshot_id"],
            ["id"],
            ondelete="CASCADE",
        )
    with op.batch_alter_table("recommendations") as batch_op:
        batch_op.create_foreign_key(
            "fk_recommendations_resolved_snapshot_id_risk_analyses",
            "risk_analyses",
            ["resolved_snapshot_id"],
            ["id"],
            ondelete="SET NULL",
        )
    with op.batch_alter_table("recommendations") as batch_op:
        batch_op.create_foreign_key(
            "fk_recommendations_last_seen_risk_id_risks",
            "risks",
            ["last_seen_risk_id"],
            ["id"],
            ondelete="CASCADE",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recommendations") as batch_op:
        batch_op.drop_constraint("fk_recommendations_sprint_id_sprints", type_="foreignkey")
        batch_op.drop_constraint(
            "fk_recommendations_last_seen_snapshot_id_risk_analyses", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_recommendations_resolved_snapshot_id_risk_analyses", type_="foreignkey"
        )
        batch_op.drop_constraint("fk_recommendations_last_seen_risk_id_risks", type_="foreignkey")
        batch_op.drop_constraint("ck_recommendations_observation_count_positive", type_="check")
    op.drop_index(op.f("ix_recommendations_sprint_id"), table_name="recommendations")
    op.drop_index("ix_recommendations_scope_active", table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_resolved_snapshot_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_last_seen_snapshot_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_last_seen_risk_id"), table_name="recommendations")
    op.drop_column("recommendations", "latest_confidence")
    op.drop_column("recommendations", "latest_score")
    op.drop_column("recommendations", "latest_severity")
    op.drop_column("recommendations", "latest_evidence")
    op.drop_column("recommendations", "observation_count")
    op.drop_column("recommendations", "resolved_at")
    op.drop_column("recommendations", "resolved_snapshot_id")
    op.drop_column("recommendations", "last_seen_risk_id")
    op.drop_column("recommendations", "last_seen_snapshot_id")
    op.drop_column("recommendations", "sprint_id")
    # ### end Alembic commands ###
